language: node_js
node_js:
  - 6.9.4
install:
  - npm uninstall -g @angular/cli
  - npm cache clean
  - npm install -g @angular/cli@latest
  - npm install --save-dev @angular/cli@latest
  - npm install
script:
  - ng build
  - cd dist
  - ls -al
